#! /bin/csh -f
# VASP run command
# user settting
set vasp_adress = $HOME'/vasp/vasp.5.4.1/bin/vasp_std'
set pseudo_potential_adress = $HOME'/vasp/potpaw_PBE'
#set vasp_adress = $HOME'/vasp/vasp.5.3/vasp'
set boltztrap_adress = $HOME'/boltztrap-1.2.5'
set __mpirun__ = "mpirun"
#if you get libraries form Ubuntu Software center, I reccommend below,
#set __mpirun__ = "mpirun.openmpi"
set file    = `pwd`
set file    = $file:t
# Automatically setting
set num_core = `grep 'core id' /proc/cpuinfo | sort -u | wc -l`
setenv OMP_NUM_THREADS 1
#
# boltztrap input making
if ( -f ${file}.py ) then
  echo "already "${file}".py"
else
cp ${boltztrap_adress}/util/vasp2boltz.py vasp2boltz.py
cat << EOF > ${file}.py
from ase import io
from ase.lattice.spacegroup import Spacegroup
import vasp2boltz

ao = io.read('POSCAR')
# If you do not have spglib installed, you need to add the spacegroup no.
# e.g. sg = Spacegroup(216) for the 'F -4 3 m' space group
# If you use the conventional cell rather than the primitive unit cell in your
# POSCAR file for e.g. I or F spacegroups, you need to add this information.

# Example 1:
#sg = Spacegroup(1)
#ao.info = {'spacegroup': sg}

# Example 2. Here the unit cell in the POSCAR file is cubic (conventional):
#sg = Spacegroup(225)
#ao.info = {'spacegroup': sg, 'unit_cell': 'conventional'}

# Read number of electrons from OUTCAR.
foundnelect = False
try:
    for line in open('OUTCAR', 'r'):
        if 'NELECT' in line:
            nelect = float(line.split()[2])
        foundnelect = True
except:
    pass
if not foundnelect:
    print 'Number of electrons not found. Please set the number manually in hte.intrans.'
    nelect = 1.0

# The remaining part takes care of writing the files required by BoltzTraP.
bs = vasp2boltz.get_vasp_bandstructure()
vasp2boltz.write_bandstructure_boltztrap(bs)
vasp2boltz.write_structure_boltztrap(ao)
vasp2boltz.write_intrans_boltztrap(n_electrons = nelect)
EOF
endif
/usr/bin/python ${file}.py
mv energies.boltztrap ${file}.energy
mv hte.intrans ${file}.intrans
mv hte.struct ${file}.struct
cp ${file}.intrans ${file}_temp.intrans
sed -e 's/800. 50./800. 10./g' ${file}_temp.intrans > ${file}.intrans
#
# run boltztrap
$boltztrap_adress/src/x_trans BoltzTraP
#
# boltztrap plot
# get data for every K
awk '{if($1=="#"){print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10}else{print ($1*13.606),$2,$3,$4,($5*1000*1000),$6,(1.0/$7),$8,$9,$10}}' ${file}.trace > ${file}_eV.trace
grep ' 10.0000'  ${file}_eV.trace > output_eV_10K.txt
grep ' 300.0000' ${file}_eV.trace > output_eV_300K.txt
grep ' 600.0000' ${file}_eV.trace > output_eV_600K.txt
# sigxx
cp ${file}.sigxx ${file}_temp.sigxx
awk '{print ($1*13.606),$2,$3,$4,$5,$6,$7,$8,$9,$10}' ${file}_temp.sigxx > sigxx_eV.txt
#
# seebeck coefficient (microV/K vs. eV)
set file     = `pwd`
set filename = $file:t
set psformat = "_seebeck.ps"
set epsformat = "_seebeck.eps"
gnuplot -persist << EOF
set title "$filename"
set zeroaxis
set xlabel "Chemical Potential, {/Symbol-Italic m} (eV)"
set ylabel "Seebeck coefficient, {/Italic S} ({/Symbol m}VK^-^1)"
p "output_eV_10K.txt" u 1:5 w l t "10 K", "output_eV_300K.txt" u 1:5 w l t "300 K", "output_eV_600K.txt" u 1:5 w l t "600 K"

#set size 1.0,1.0
#set terminal postscript color enhanced "Arial" 30
#set out "$filename$psformat"

set size 1.5,2.1
set terminal postscript eps color enhanced "Arial" 30
set out "$filename$epsformat"

replot
set terminal x11
EOF
#
# conductivity/lifetime vs. eV
set file     = `pwd`
set filename = $file:t
set psformat = "_sigma.ps"
set epsformat = "_sigma.eps"
gnuplot -persist << EOF
set title "$filename"
set zeroaxis
set xlabel "Chemical Potential, {/Symbol-Italic m} (eV)"
set ylabel "Electrical conductivity, {/Symbol s} / {/Symbol t} ({/Symbol W}^-^1m^-^1s^-^1)"
p "output_eV_10K.txt" u 1:6 w l t "10 K", "output_eV_300K.txt" u 1:6 w l t "300 K", "output_eV_600K.txt" u 1:6 w l t "600 K"

#set size 1.0,1.0
#set terminal postscript color enhanced "Arial" 30
#set out "$filename$psformat"

set size 1.5,2.1
set terminal postscript eps color enhanced "Arial" 30
set out "$filename$epsformat"

replot
set terminal x11
EOF
#
# Electronic thermal conductivity vs. eV
set file     = `pwd`
set filename = $file:t
set psformat = "_kel.ps"
set epsformat = "_kel.eps"
gnuplot -persist << EOF
set title "$filename"
set zeroaxis
set xlabel "Chemical Potential, {/Symbol-Italic m} (eV)"
set ylabel "Electrical thermal conductivity, {/Symbol k}^0 (Wm^-^1K^-^1s^-^1)"
p "output_eV_10K.txt" u 1:8 w l t "10 K", "output_eV_300K.txt" u 1:8 w l t "300 K", "output_eV_600K.txt" u 1:8 w l t "600 K"

#set size 1.0,1.0
#set terminal postscript color enhanced "Arial" 30
#set out "$filename$psformat"

set size 1.5,2.1
set terminal postscript eps color enhanced "Arial" 30
set out "$filename$epsformat"

replot
set terminal x11
EOF
#
# eV vs. inverse Hall coefficient
set file     = `pwd`
set filename = $file:t
set psformat = "_n.ps"
set epsformat = "_n.eps"
gnuplot -persist << EOF
set title "$filename"
set zeroaxis
set xlabel "Inverse Hall coefficient, {/Italic R_H}^-^1} (e.unitcell^-^1)"
#set xlabel "Inverse Hall coefficient and number of carriers n (density of states), {/Italic R_H}^-^1} and {/Italic n} (e.unitcell^-^1)"
set ylabel "Chemical Potential, {/Symbol-Italic m} (eV)"
p "output_eV_10K.txt" u 7:1 w l t "R_H^-^1 at 10 K", "output_eV_300K.txt" u 7:1 w l t "R_H^-^1 at 300 K", "output_eV_600K.txt" u 7:1 w l t "R_H^-^1 at 600 K"
#p "output_eV_10K.txt" u 7:1 w l t "R_H^-^1 at 10 K", "output_eV_300K.txt" u 7:1 w l t "R_H^-^1 at 300 K", "output_eV_600K.txt" u 7:1 w l t "R_H^-^1 at 600 K", "output_eV_10K.txt" u 4:1 w l t "n at 10 K", "output_eV_300K.txt" u 4:1 w l t "n at 300 K", "output_eV_600K.txt" u 4:1 w l t "n at 600 K"

#set size 1.0,1.0
#set terminal postscript color enhanced "Arial" 30
#set out "$filename$psformat"

set size 1.5,2.1
set terminal postscript eps color enhanced "Arial" 30
set out "$filename$epsformat"

replot
set terminal x11
EOF
#
# sigxx vs. eV
set file     = `pwd`
set filename = $file:t
set psformat = "_sigxx.ps"
set epsformat = "_sigxx.eps"
gnuplot -persist << EOF
set title "$filename"
set zeroaxis
set xlabel "Chemical Potential, {/Symbol-Italic m} (eV)"
set ylabel "Electrical conductivity, {/Symbol s} / {/Symbol t} ({/Symbol W}^-^1m^-^1s^-^1)"
p "sigxx_eV.txt" u 1:2 w l t "xx", "sigxx_eV.txt" u 1:3 w l t "xy", "sigxx_eV.txt" u 1:4 w l t "xz", "sigxx_eV.txt" u 1:5 w l t "yx", "sigxx_eV.txt" u 1:6 w l t "yy", "sigxx_eV.txt" u 1:7 w l t "yz", "sigxx_eV.txt" u 1:8 w l t "zx", "sigxx_eV.txt" u 1:9 w l t "zy", "sigxx_eV.txt" u 1:10 w l t "zz"

#set size 1.0,1.0
#set terminal postscript color enhanced "Arial" 30
#set out "$filename$psformat"

set size 1.5,2.1
set terminal postscript eps color enhanced "Arial" 30
set out "$filename$epsformat"

replot
set terminal x11
EOF
#
